version: '3.8'
services:
  db:
    container_name: db-mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SMART-MANAGEMENT
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 15
    volumes:
      - ./database/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    ports:
      - "3306:3306"

  backend:
    container_name: app-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "3000:3000"
